steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
    - '-f'
    - 'latest/php8.2/apache/Dockerfile'  # Replace with the actual path to your Dockerfile
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8_config/wordpress-cloudsql-deploy.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'