steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
    - '-f'
    - 'latest/php8.2/apache/Dockerfile'  # Replace with the actual path to your Dockerfile
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=wordpress-cloudsql-deploy.yaml
  - --image=gcr.io/project-id/wordpress:$COMMIT_SHA
  - --location=location
  - --cluster=wordpress-cluster
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'