steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    # args:
    #   - 'apply'
    #   - '-f'
    #   - 'k8s/wordpress-cloudsql-deploy'
    # env:
    #   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    #   - 'CLOUDSDK_CONTAINER_CLUSTER=[YOUR_CLUSTER_NAME]'